import { Injectable, NotFoundException } from '@nestjs/common';
import type { $Enums, Prisma } from '@prisma/client';
import { PrismaService } from '../../core/database/prisma.service';
import { TenantContext } from '../../core/tenancy/tenant-context';
import { AuditService } from '../../core/audit';
import { StorageService } from '../../core/storage/storage.service';
import { ReferenceCodeService } from '../../core/common/reference-code.service';
import { PdfService } from '../../core/pdf';
import type { GenerateVoucherDto } from './dto/vouchers.dto';

/**
 * Generates vouchers. The rendered document is stored as an HTML artifact in
 * object storage (PDF rendering is a pluggable downstream step — swap the
 * renderer to produce PDF without changing this flow).
 */
@Injectable()
export class VouchersService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly ctx: TenantContext,
    private readonly audit: AuditService,
    private readonly storage: StorageService,
    private readonly refCodes: ReferenceCodeService,
    private readonly pdf: PdfService,
  ) {}

  listForBooking(bookingId: string) {
    return this.prisma.db.voucher.findMany({ where: { bookingId }, orderBy: { createdAt: 'desc' } });
  }

  async generate(bookingId: string, dto: GenerateVoucherDto) {
    const tenantId = this.ctx.tenantId!;
    const booking = await this.prisma.db.booking.findFirst({
      where: { id: bookingId },
      include: { lead: true, hotelBookings: true, transportBookings: true },
    });
    if (!booking) throw new NotFoundException({ code: 'NOT_FOUND', error: 'Booking not found' });

    const referenceCode = await this.refCodes.next('VCH', tenantId, new Date().getFullYear(), () =>
      this.prisma.db.voucher.count(),
    );
    const payload = {
      type: dto.type,
      booking: booking.referenceCode,
      customer: booking.lead.name,
      destination: booking.destination,
      travel: { start: booking.travelStart, end: booking.travelEnd },
      hotels: booking.hotelBookings.map((h) => ({ name: h.hotelName, room: h.roomType, checkIn: h.checkIn })),
      transport: booking.transportBookings.map((t) => ({ vehicle: t.vehicleType, date: t.serviceDate })),
    };

    const html = this.renderHtml(referenceCode, dto.type, payload);

    // Render a real PDF when Chromium is available; otherwise store the HTML.
    const pdf = await this.pdf.fromHtml(html);
    const ext = pdf ? 'pdf' : 'html';
    const contentType = pdf ? 'application/pdf' : 'text/html';
    const body: Buffer | string = pdf ?? html;
    const key = this.storage.buildKey(tenantId, 'voucher', `${referenceCode}.${ext}`);
    await this.storage.putObject(key, body, contentType);

    const file = await this.prisma.db.file.create({
      data: {
        tenantId,
        bucket: 'travelos',
        objectKey: key,
        filename: `${referenceCode}.${ext}`,
        contentType,
        sizeBytes: BigInt(pdf ? pdf.length : Buffer.byteLength(html)),
        category: 'voucher',
        ownerResourceType: 'booking',
        ownerResourceId: bookingId,
        createdBy: this.ctx.userId,
      },
    });

    const voucher = await this.prisma.db.voucher.create({
      data: {
        tenantId,
        bookingId,
        type: dto.type as $Enums.VoucherType,
        referenceCode,
        status: 'generated',
        pdfFileId: file.id,
        issuedTo: dto.issuedTo ?? booking.lead.name,
        payload: payload as Prisma.InputJsonValue,
        generatedAt: new Date(),
        createdBy: this.ctx.userId,
      },
    });
    await this.audit.record({ action: 'created', resourceType: 'voucher', resourceId: voucher.id });
    return voucher;
  }

  async getDownloadUrl(id: string): Promise<{ url: string }> {
    const voucher = await this.prisma.db.voucher.findFirst({ where: { id } });
    if (!voucher?.pdfFileId) throw new NotFoundException({ code: 'NOT_FOUND', error: 'Voucher not generated' });
    const file = await this.prisma.db.file.findFirst({ where: { id: voucher.pdfFileId } });
    if (!file) throw new NotFoundException({ code: 'NOT_FOUND', error: 'File missing' });
    return { url: await this.storage.getDownloadUrl(file.objectKey) };
  }

  private renderHtml(ref: string, type: string, payload: Record<string, unknown>): string {
    return `<!doctype html><html><head><meta charset="utf-8"><title>Voucher ${ref}</title>
<style>body{font-family:system-ui,sans-serif;max-width:720px;margin:40px auto;color:#0f172a}
h1{font-size:20px}table{width:100%;border-collapse:collapse}td{padding:6px;border-bottom:1px solid #e2e8f0}</style></head>
<body><h1>${type.toUpperCase()} VOUCHER — ${ref}</h1>
<pre>${JSON.stringify(payload, null, 2)}</pre>
<p>Generated by TravelOS AI.</p></body></html>`;
  }
}
